apiVersion: v1
kind: Service
metadata:
  name: exatauser
  labels:
    run: exatauser
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort
  selector:
    run: exatauser

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exatauser
spec:
  replicas: 2
  template: 
    metadata:
      labels:
        run: exatauser
    spec:
      containers:
      - name: exatauser
        image: us.icr.io/iux-miaspace1/microswsuser
        ports:
        - containerPort: 8080